name: stellapro
description: "Plataforma B2B2C para estofarias - StellaPro"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

